apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: deployment-viewer
rules:
- apiGroups: ["", "apps"]
  resources: ["pods","services", "deployments"]
  verbs: ["get", "list", "watch"]
